### ISSUE TITLE
[improvement] SBOM extension command sbom:cyclonedx - add new --no-build-requires command line argument

### ISSUE THREAD

**Issue by johan-boule** [conan-io/conan-extensions#158]
I would like propose some code to add a new command line option to the SBOM extension command sbom:cyclonedx to allow to filter the graph node based on dependency context (host and/or build).
While Ken Thompson's thesis about injecting a virus into a compiler is interesting, we'd like to ignore that and generate an SBOM that doesn't include the build_requires :-)
The change to do that is simple but I'd like first to have guidance about how the command line option should be presented. i.e. how to name it, what syntax should it have etc.
Also, in the source code of the extension, there's a FIXME note about some --build-require option, can someone explain what this is about ?

**Comment by memsharded** [comment]
Thanks for the suggestion @johan-boule 

I think this makes sense and it is a valid use case. Also agree that the implementation should be pretty straightforward, so it would be mostly about the UX/UI.

I don't think that generating the build-context only SBOM makes any sense, so probably we need more a boolean argument something like ``--ignore-build-requires``, ``--no-build-requires``, ``--no-build-context`` or ``--only-host``?

As this extension is experimental, and in any case these extensions are not aimed for stability yet, but users should fork them and use them from their forks, I'd probably wouldn't discuss much about the name, ``--no-build-requires`` sounds good enough.


> Also, in the source code of the extension, there's a FIXME note about some --build-require option, can someone explain what this is about ?

The ``--build-require`` argument in commands like ``conan create`` changes how the package is created, because it puts the current consumer in the "build" context, intended to be used as ``tool_requires`` when consumed. At the moment this sbom command is not honoring that argument at all apparently.
